
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/bb-user-service?serverTimezone=Asia/Seoul
    username: root
    password: k1651227
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

feign:
  client:
    default:
      url: http://localhost:8082
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

service:
  coupon:
    domain : ${service.coupon.domain}
  likes:
    domain : ${servive.likes.domain}