server:
  port: 8600
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: user-service
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"
          - "health"
