server:
  port: 8600
spring:
  application:
    name: user-service
  config:
    activate:
      on-profile: prod
    import: optional:configserver:http://config-service:8888


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"