spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${spring.datasoure.url}
    username: ${spring.datasource.username}
    password: ${spring.datasoure.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

service:
  coupon:
    domain : ${service.coupon.domain}
  likes:
    domain : ${servive.likes.domain}