server:
  port: 8600
spring:
  application:
    name: user-service
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://localhost:8888


  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"